In [2]:
# favorite example

# cam2, start_index = 20, end_index = 23

# point №40
# it corresponds to instance 53 (image 20)
# it corresponds to instance 45 (image 21)
# it corresponds to instance 53 (image 22)

In [3]:
from pathlib import Path

from pcd_dataset.kitti_dataset import KittiDataset

dataset_path = 'dataset/'
sequence = '00'
sam_labels_path = Path.cwd().joinpath('pipeline', 'vfm-labels', 'sam', sequence)

kitti = KittiDataset(dataset_path, sequence, sam_labels_path)

In [4]:
from mapping.simple_mapping import SimpleMapping

sm = SimpleMapping(kitti)
coo_matrix, pcds = sm.get_combined_labeled_point_clouds('cam2', 20, 23)

INFO:simple_mapping.SimpleMapping:Image 20 processed


0.0


INFO:simple_mapping.SimpleMapping:Image 21 processed


0.0


INFO:simple_mapping.SimpleMapping:Image 22 processed


61.0


In [5]:
from mapping.sparse_matrix_utils import construct_coo_matrix_for_multiple_views

coo_result = construct_coo_matrix_for_multiple_views(coo_matrix, 20)

In [6]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore', sparse_output=True)

In [7]:
enc.fit((coo_result.T).toarray())

OneHotEncoder(handle_unknown='ignore')

In [8]:
enc.categories_

[array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 28., 29., 30., 31., 32., 33., 34., 35., 37., 38., 39., 40.,
        42., 43., 44., 45., 46., 48., 49., 50., 51., 53., 54., 56., 57.,
        58., 59., 62., 63., 64., 67., 68., 69., 71., 73., 74., 75., 76.,
        77., 78., 79., 80.]),
 array([ 0.,  2.,  3.,  4.,  5.,  6.,  7., 10., 11., 12., 13., 14., 15.,
        16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 39., 40., 41., 42.,
        43., 44., 45., 47., 49., 50., 51., 52., 54., 55., 56., 58., 59.,
        60., 62., 64., 65., 67., 69., 71., 72., 73., 74.]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
        40., 41., 42., 43., 44., 4

In [9]:
s = enc.transform(coo_result.T.toarray()).toarray()

In [10]:
len(s)

832606

In [10]:
# for itr in range(len(s[40])):
#     if s[40, itr] != 0.0:
#         print(itr)

48
110
182


In [11]:
p = enc.inverse_transform(s)

k = 0
for itr in range(len(p)):
    if (p[itr] == [0.0, 0.0, 0.0]).all():
        k = k + 1
        
print(len(p) - k)

92411


In [12]:
pcddd = pcds[0] + pcds[1] + pcds[2]

In [13]:
# p[40]

In [14]:
pcddd.points[9]

array([-8.54871034, -1.86390096, 39.59046832])

In [15]:
import numpy as np

p = enc.inverse_transform(s)
# points = np.zeros((len(p) - k), dtype=int)
points = []
map = {}

k = 0
i = 0
for itr in range(len(p)):
    if (p[itr] == [0.0, 0.0, 0.0]).all():
        k = k + 1
    else:
        if k < 10:
            print(itr)
        points.append(pcddd.points[itr])
        dict1 = {itr:i}
        map.update(dict1)
        # map.update({'old_pcd': itr, 'new_pcd': i})
        i = i + 1

0
1
2
3
4
5


In [16]:
len(map)

92411

In [17]:
p[3692]
# 3692 - 990

array([ 0., 25., 15.])

In [17]:
map

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 20: 6,
 21: 7,
 22: 8,
 23: 9,
 24: 10,
 25: 11,
 26: 12,
 27: 13,
 28: 14,
 32: 15,
 33: 16,
 34: 17,
 35: 18,
 36: 19,
 37: 20,
 38: 21,
 39: 22,
 40: 23,
 41: 24,
 42: 25,
 43: 26,
 44: 27,
 45: 28,
 46: 29,
 47: 30,
 48: 31,
 49: 32,
 50: 33,
 51: 34,
 52: 35,
 53: 36,
 54: 37,
 55: 38,
 56: 39,
 57: 40,
 58: 41,
 59: 42,
 60: 43,
 61: 44,
 62: 45,
 63: 46,
 64: 47,
 65: 48,
 66: 49,
 67: 50,
 68: 51,
 69: 52,
 70: 53,
 71: 54,
 72: 55,
 73: 56,
 74: 57,
 75: 58,
 76: 59,
 77: 60,
 78: 61,
 79: 62,
 80: 63,
 81: 64,
 82: 65,
 83: 66,
 84: 67,
 85: 68,
 86: 69,
 87: 70,
 88: 71,
 89: 72,
 90: 73,
 91: 74,
 92: 75,
 93: 76,
 94: 77,
 95: 78,
 96: 79,
 97: 80,
 98: 81,
 99: 82,
 100: 83,
 101: 84,
 102: 85,
 103: 86,
 104: 87,
 105: 88,
 106: 89,
 107: 90,
 108: 91,
 109: 92,
 110: 93,
 111: 94,
 112: 95,
 113: 96,
 114: 97,
 115: 98,
 1153: 99,
 1154: 100,
 1155: 101,
 1156: 102,
 1157: 103,
 1158: 104,
 1159: 105,
 1160: 106,
 1161: 107,
 1

In [19]:
len(s)

832606

In [20]:
len(map.keys())

92411

In [18]:
sresss = []

for itr in range(len(s)):
    if itr in map.keys():
        sresss.append(s[itr])
        

In [19]:
len(sresss)

92411

In [20]:
ooo = enc.inverse_transform(sresss)
print(ooo[990])

[ 0. 25. 15.]


In [21]:
import open3d as o3d

pcd_baby = o3d.geometry.PointCloud()
pcd_baby.points = o3d.utility.Vector3dVector(points)

In [22]:
len(pcd_baby.points)

92411

In [23]:
downpcd = pcd_baby.voxel_down_sample(voxel_size=0.05)
# o3d.visualization.draw_geometries([downpcd])

In [24]:
len(downpcd.points)

63758

In [27]:
map

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 20: 6,
 21: 7,
 22: 8,
 23: 9,
 24: 10,
 25: 11,
 26: 12,
 27: 13,
 28: 14,
 32: 15,
 33: 16,
 34: 17,
 35: 18,
 36: 19,
 37: 20,
 38: 21,
 39: 22,
 40: 23,
 41: 24,
 42: 25,
 43: 26,
 44: 27,
 45: 28,
 46: 29,
 47: 30,
 48: 31,
 49: 32,
 50: 33,
 51: 34,
 52: 35,
 53: 36,
 54: 37,
 55: 38,
 56: 39,
 57: 40,
 58: 41,
 59: 42,
 60: 43,
 61: 44,
 62: 45,
 63: 46,
 64: 47,
 65: 48,
 66: 49,
 67: 50,
 68: 51,
 69: 52,
 70: 53,
 71: 54,
 72: 55,
 73: 56,
 74: 57,
 75: 58,
 76: 59,
 77: 60,
 78: 61,
 79: 62,
 80: 63,
 81: 64,
 82: 65,
 83: 66,
 84: 67,
 85: 68,
 86: 69,
 87: 70,
 88: 71,
 89: 72,
 90: 73,
 91: 74,
 92: 75,
 93: 76,
 94: 77,
 95: 78,
 96: 79,
 97: 80,
 98: 81,
 99: 82,
 100: 83,
 101: 84,
 102: 85,
 103: 86,
 104: 87,
 105: 88,
 106: 89,
 107: 90,
 108: 91,
 109: 92,
 110: 93,
 111: 94,
 112: 95,
 113: 96,
 114: 97,
 115: 98,
 1153: 99,
 1154: 100,
 1155: 101,
 1156: 102,
 1157: 103,
 1158: 104,
 1159: 105,
 1160: 106,
 1161: 107,
 1

In [25]:
sresss = []
mapsresss = {}
u = 0
for itr in range(len(s)):
    if itr in map.keys():
        sresss.append(s[itr])
        dict12 = {itr:len(sresss) - 1}
        mapsresss.update(dict12)

In [26]:
len(sresss)

92411

In [27]:
len(pcd_baby.points)

92411

In [29]:
mapsresss

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 20: 6,
 21: 7,
 22: 8,
 23: 9,
 24: 10,
 25: 11,
 26: 12,
 27: 13,
 28: 14,
 32: 15,
 33: 16,
 34: 17,
 35: 18,
 36: 19,
 37: 20,
 38: 21,
 39: 22,
 40: 23,
 41: 24,
 42: 25,
 43: 26,
 44: 27,
 45: 28,
 46: 29,
 47: 30,
 48: 31,
 49: 32,
 50: 33,
 51: 34,
 52: 35,
 53: 36,
 54: 37,
 55: 38,
 56: 39,
 57: 40,
 58: 41,
 59: 42,
 60: 43,
 61: 44,
 62: 45,
 63: 46,
 64: 47,
 65: 48,
 66: 49,
 67: 50,
 68: 51,
 69: 52,
 70: 53,
 71: 54,
 72: 55,
 73: 56,
 74: 57,
 75: 58,
 76: 59,
 77: 60,
 78: 61,
 79: 62,
 80: 63,
 81: 64,
 82: 65,
 83: 66,
 84: 67,
 85: 68,
 86: 69,
 87: 70,
 88: 71,
 89: 72,
 90: 73,
 91: 74,
 92: 75,
 93: 76,
 94: 77,
 95: 78,
 96: 79,
 97: 80,
 98: 81,
 99: 82,
 100: 83,
 101: 84,
 102: 85,
 103: 86,
 104: 87,
 105: 88,
 106: 89,
 107: 90,
 108: 91,
 109: 92,
 110: 93,
 111: 94,
 112: 95,
 113: 96,
 114: 97,
 115: 98,
 1153: 99,
 1154: 100,
 1155: 101,
 1156: 102,
 1157: 103,
 1158: 104,
 1159: 105,
 1160: 106,
 1161: 107,
 1

In [ ]:
sresss2 = []
for itr in range(len(sresss)):
    for yy in range(len(downpcd.points)):
        if itr

In [ ]:
inds = np.where(
    (points_coord[:, 0] < img_width) & (points_coord[:, 0] >= 0) &
    (points_coord[:, 1] < img_height) & (points_coord[:, 1] >= 0) &
    (points_coord[:, 2] > 0)
)[0]

In [25]:
import numpy as np
len(np.asarray(pcds[0].points))

277369

In [12]:
import utils.pcd_utils
pcd = utils.pcd_utils.visualize_from_one_hot_encoding(s, enc, pcds, 20, 20)

[53. 45. 53.]
53.0
832606
PointCloud with 277369 points.
277369


In [12]:
import open3d as o3d

o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


In [15]:
i = enc.inverse_transform(s)

start = 20
end = 46
for point in range(start, end) :
    print("{} : {}".format(point, i[point]))

20 : [15.  0.  0.]
21 : [15. 17.  0.]
22 : [15. 17. 15.]
23 : [15. 17. 15.]
24 : [15. 17. 15.]
25 : [15. 17. 15.]
26 : [15. 17. 15.]
27 : [15. 17. 15.]
28 : [ 0.  0. 15.]
29 : [0. 0. 0.]
30 : [0. 0. 0.]
31 : [0. 0. 0.]
32 : [53. 45.  0.]
33 : [53. 45.  0.]
34 : [53. 45. 53.]
35 : [53. 45. 53.]
36 : [53. 45. 53.]
37 : [53. 45. 53.]
38 : [53. 45. 53.]
39 : [53. 45. 53.]
40 : [53. 45. 53.]
41 : [53. 45. 53.]
42 : [53. 45. 53.]
43 : [53. 45. 53.]
44 : [53. 45. 53.]
45 : [ 7.  4. 53.]


In [33]:
len(sresss)

92411

In [28]:
from sklearn.metrics.pairwise import pairwise_distances
dist555ready = pairwise_distances(sresss)

In [29]:
dist555ready.shape

(92411, 92411)

In [21]:
dist555ready[26, 37]

2.449489742783178

In [27]:
dist555.shape

(450, 450)

In [11]:
dist = np.exp(dist555)

In [14]:
dist555

array([[0.        , 0.        , 0.        , ..., 1.41421356, 1.41421356,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 1.41421356, 1.41421356,
        1.41421356],
       [0.        , 0.        , 0.        , ..., 1.41421356, 1.41421356,
        1.41421356],
       ...,
       [1.41421356, 1.41421356, 1.41421356, ..., 0.        , 0.        ,
        0.        ],
       [1.41421356, 1.41421356, 1.41421356, ..., 0.        , 0.        ,
        0.        ],
       [1.41421356, 1.41421356, 1.41421356, ..., 0.        , 0.        ,
        0.        ]])

In [13]:
dist

array([[1.        , 1.        , 1.        , ..., 4.11325038, 4.11325038,
        4.11325038],
       [1.        , 1.        , 1.        , ..., 4.11325038, 4.11325038,
        4.11325038],
       [1.        , 1.        , 1.        , ..., 4.11325038, 4.11325038,
        4.11325038],
       ...,
       [4.11325038, 4.11325038, 4.11325038, ..., 1.        , 1.        ,
        1.        ],
       [4.11325038, 4.11325038, 4.11325038, ..., 1.        , 1.        ,
        1.        ],
       [4.11325038, 4.11325038, 4.11325038, ..., 1.        , 1.        ,
        1.        ]])

In [26]:
dist555ready.shape

(92411, 92411)

In [1]:
len(pcd_baby.points)

NameError: name 'pcd_baby' is not defined

In [30]:
dist555ready.shape[0]

92411

In [31]:
from scipy import sparse
t = sparse.identity(dist555ready.shape[0])

In [ ]:
import numpy as np
# labels = np.arange(450)
# print(labels)

from awesome_normalized_cut import normalized_cut

u = normalized_cut(dist555ready, pcd_baby.points, 0.0000001)

In [1]:
u[0]

NameError: name 'u' is not defined

In [12]:
# 1) выбросить ненужные точки. создать новое облако и мапу старое - новое
# 2) voxel_down_sample применить к маленькому облаку
# применить к нему граф кат, раскрасить по кластерам ИСХОДНОЕ маленькое облако с новыми инстансами
# 3) kd деревья почитать чтобы найти соседей

In [13]:
u

[array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178

In [ ]:
import scipy.spatial
res = scipy.spatial.distance.cdist(s, s, 'euclidean')

In [1]:
res

NameError: name 'res' is not defined

In [ ]:
# найти функцию которая на разреженных матрицах считает расстояния
# на каком-то этапе надо выкинуть точки которые не попадают ни в один снимок